apiVersion: v1
kind: Secret
metadata:
    name: secret-using-sops
type: Opaque
data:
    password: ENC[AES256_GCM,data:01GhoLO7Pv92ufL+Ufqbow==,iv:02Q00Syvkt8a5BTMBhV7YwcwvFPFZdar7pFWE4kFaxQ=,tag:Es295TznE47SWSYAdkQPLw==,type:str]
sops:
    age:
        - recipient: age16g0yfd7qeg2e9x9esrj4yfaraqutqr4m7rwtqudpwx6kn6ak5a2qrrmkvs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaDE5UzZpajJsL3BXaThN
            dmsyaGVGWHNjWXpodm9EUEluMzBsanZuelJJCk1qdEZaanBOTHY3RXRyTXV5Nzdi
            eklhQXBaKzkxb0ZrQmtXWnZRbEN3OVUKLS0tIFdyT3hYZjhCZ0pnSDY3MThUaWdL
            THJMOUFuU0E4RU94Y0FXL1pzdGpEOEkK36TIf+wb4gl39opdcrxpu/w4VyHZxQuP
            UihXrZ8LJQAvjrTzM/RIX+7+XkPrczxofIzlrxV2gVYRarUOOXHkcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T08:18:21Z"
    mac: ENC[AES256_GCM,data:9rEwDg/i67EWsvDTQosV6I/KEw9XAW5hFoVqeFCvPLtGchd4xOAvTAiV5vSwgAc2jgva7nt6oML1brP+dzwnKJgJidLHJ6wYkFMbgkmHMmUYJ7bQy/VtXftDtKiQD850u4ZkpWw6eih2cFNoK9JxRQ8FWKuve+aedauJXBE/efI=,iv:nvbkFaEEYpAlANKaqT7mfIwQVcFIntZOCP30/yydJ28=,tag:bigNJu2r2mb0gCqKAF1v4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
